### PR TITLE
Add stdout output

### PR DESCRIPTION
**Pull request by tlvince**
Unfortunately [GitHub Advanced Security](https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security) (for the SARIF feature) is unavailable for private repos on GitHub.com. As an alternative, Slither's markdown report can be used.

This sets `outputs.stdout` (which is required to be a single-line string) and adds example usage to the readme. See https://github.com/tlvince/hardhat-project/pull/1#issuecomment-1147434360 to see how it looks.

### CODE REVIEW

**Comment by stephenctw** [comment]
Nice work! I faced the same issue that Github Advanced Security is not available for private repos. The way I worked around it is to add another step to parse the SARIF report into github annotation.
https://github.com/marketplace/actions/process-sarif-file

**Comment by abcfy2** [comment]
Really need this feature, we need to use the markdown report. Please merge this PR. Thanks.

**Comment by elopez** [comment]
Thanks for the PR @tlvince! I've merged `dev` to update the branch, updated the README to match, and modified the escaping code to use the new [multiline strings feature](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings) on Actions output. I think we can merge this now, unless you have any objections to the changes I did.

**Comment by tlvince** [comment]
lgtm 👍🏻

**Pull request merged**
