### PR TITLE
Mark git repositories as safe inside the slither-action container

### PR DESCRIPTION
**Pull request by elopez**
See https://github.com/actions/runner/issues/2033

Fixes: #49

### CODE REVIEW

**Comment by CodeSandwich** [comment]
Yes, it's working :tada: The successful CI run: https://github.com/radicle-dev/drips-contracts/actions/runs/4136557972/jobs/7150586465

**Review by almost-llamas — APPROVED** [review]

**Comment by CodeSandwich** [comment]
This seems to be a fairly important fix, I don't know what was changed in GH runners, but it probably broke more than just my CI. Are you planning to make a release of a new version so the fix is more accessible?

**Comment by almost-llamas** [comment]
Confirm that it's working on my CI too, but Github status does not work as expected. It always marked job status as passing even finding is detected.  Not sure if this is a separated issue.

**Comment by elopez** [comment]
@almost-llamas that appears to be a separate issue introduced with #13; I merged a fix in #51 today. Let me know if you still experience that when using the `dev` branch.

@CodeSandwich I'll try and prepare a new release early next week 👍

**Comment by almost-llamas** [comment]
> @almost-llamas that appears to be a separate issue introduced with #13; I merged a fix in #51 today. Let me know if you still experience that when using the `dev` branch.
> 
> @CodeSandwich I'll try and prepare a new release early next week 👍

Thanks! It works flawlessly.  🎉

**Pull request merged**
