### PR TITLE
Add pnpm support

### PR DESCRIPTION
**Pull request by 0xCLARITY**
Add PNPM support to the GH Action.

I had to explicitly call `pnpm config set store-dir` to avoid a folder permissions issue with whatever the default `store-dir` location is.

### CODE REVIEW

**Comment by elopez** [comment]
This looks good, thanks! Can you share a link to a sample project using pnpm? It would be handy to have one for testing future changes.

**Comment by hansbergren** [comment]
The project I'm working with right now is closed-source. We might open it up later? If you feel it's blocking to have a pnpm sample project I can try to put one together when I have a light afternoon.

**Comment by elopez** [comment]
We can go ahead with this, but if you can provide one it'd certainly help to make sure the support doesn't break. I did a quick search for any open source solidity projects using pnpm but didn't find any. It doesn't have to be anything particularly complex or functional, something simple with a dummy contract that showcases pnpm should be okay for testing.

**Comment by hansbergren** [comment]
Makes sense. I can throw together something with a dummy contract.

**Comment by 0xCLARITY** [comment]
Here's an example repo. The PR uses my branch for the GH action since it has `pnpm` support

**Pull request merged**
